/// Flutter icons CustomFonts
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomFonts
///      fonts:
///       - asset: fonts/CustomFonts.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class CustomFonts {
  CustomFonts._();

  static var kFontFam = 'CustomFonts';

   IconData github_circled =  IconData(0xe800, fontFamily: kFontFam);
   IconData linkedin =  IconData(0xe801, fontFamily: kFontFam);
  IconData facebook =  IconData(0xf052, fontFamily: kFontFam);
   IconData google = IconData(0xf1a0, fontFamily: kFontFam);
   IconData facebook_1 = IconData(0xf300, fontFamily: kFontFam);
}
